spring.application.name=InsurenceBackend
spring.datasource.url=jdbc:postgresql://localhost:5432/Insurance
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
